### ISSUE TITLE
Download link in Readme.md returns 404 Not Found

### ISSUE THREAD

**Issue by jps3** [obihann/archey-osx#33]
Very minor, just an "fyi". The download link "The latest stable release is 1.5" (https://github.com/obihann/archey-osx/archive/1.5.tar.gz). is returning a 404 Not Found error.

**Comment by obihann** [comment]
Oops, sorry about that. Fixed now, and thanks for the heads up.

**Comment by jps3** [comment]
Love them easy fixes. :-)
