### ISSUE TITLE
can not get IP and buttery info use `archey -c` or `archey -c -o`

### ISSUE THREAD

**Issue by w4lle** [obihann/archey-osx#41]
just like this:

                 ###
               ####                   User: w4lle
               ###                    Hostname: w4lleMacBook-Pro
       #######    #######             Distro: OS X 10.9.4
     ######################           Kernel: Darwin
    #####################             Uptime:  2:15
    ####################              Shell: /bin/zsh
    ####################              Terminal: xterm-256color
    #####################             Packages: 20
     ######################           CPU: Intel Core i5-4278U CPU @ 2.60GHz
      ####################            Memory: 8 GB
        ################              Disk: 85%
         ####     #####

OSX version 10.9.4

**Comment by obihann** [comment]
Could you run `archey -h` and let me know what version of archey you are running? Battery should be displayed for sure no matter what the flag, as long as your system has a battery (i.e. not a mac pro), however the `-o` flag will disable the IP check.

**Comment by jhersh** [comment]
mmm...buttery

**Comment by obihann** [comment]
Should be all resolved now.

**Comment by obihann** [comment]
This is now in 1.6.0-pr https://github.com/obihann/archey-osx/releases/tag/1.6.0-pr
