### ISSUE TITLE
[1.5.2] binary operator expected

### ISSUE THREAD

**Issue by sashkab** [obihann/archey-osx#42]
When I login, I get this:

```
$ /usr/local/bin/archey
/usr/local/bin/archey: line 132: [: q: binary operator expected

                 ###                  User: xxx
...
$ /usr/local/bin/archey --help
Archey OS X 1.5.2
...
```

Most likely related to the #29.

**Comment by obihann** [comment]
Thanks for this. I'll give your PR a quick glance over then get it into the 1.6-pre-release.

**Comment by obihann** [comment]
This is now in 1.6.0-pr https://github.com/obihann/archey-osx/releases/tag/1.6.0-pr
