### ISSUE TITLE
i can't  remaster automatically  manually

### ISSUE THREAD

**Issue by dukegod** [obihann/archey-osx#50]
every time, i open my Terminal. it can't  start auto.

i must input 'archey' in my terminal, then i can see the magical displaying infomation

**Comment by obihann** [comment]
You'll have to add it to your bashrc file or equivalent, the tool itself has no way to auto start. Look for a file named ~/.bashrc or ~/.profile.

**Comment by dukegod** [comment]
i just have the  ~/.bash_profile.

how to add "archey" to "bash_profiel",can u give me a example.like:

    # mysql
    export PATH=/usr/local/mysql/bin:$PATH

   # mongodb
    export MONGO_PATH=/usr/local/Cellar/mongodb/3.2.0
   export PATH=$PATH:$MONGO_PATH/bin
   # execute archey 
   archey

`

**Comment by obihann** [comment]
add `archey` to ~/.bash_profile,  that should do the trick.

**Comment by dukegod** [comment]
it's work, thanks.
